### ISSUE TITLE
[PE-D] Assign to interview

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-1/tp#198]
![Screen Shot 2021-10-29 at 4.43.49 PM.png](https://raw.githubusercontent.com/Leofeng10/ped/main/files/4de87b76-303f-469b-832f-a1edf95bd8a8.png)
<br>
my command is
`assign i=3 c=12 11 10 10`
<br>
I input the same candidate 10 twice, then ideally the info should only has 3 candidates listed, but it has 4

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Leofeng10/ped#4

**Comment by angnobel** [comment]
Fix in parser by removing duplciates
