### ISSUE TITLE
[PE-D] Consistent sequencing of features

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-1/tp#199]
Minor point again but would be good if the sequence of features are consistent. Eg since it starts with the job position features in the table of contents, start with job position features in command summary.
![image.png](https://raw.githubusercontent.com/yucheng11122017/ped/main/files/b606a6a0-ff6a-4e97-beca-e159acc6b01e.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: yucheng11122017/ped#17

**Comment by angnobel** [comment]
Split into 3 tables
