### ISSUE TITLE
[PE-D] GUI glitch

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-1/tp#211]
Regarding the GUI after adding an interview to a candidate, using the `add_i` command, there tends to be a glitch. However, this gets resolved after scrolling. Perhaps just something to take note of! Not a big issue. 

![Screenshot 2021-10-29 at 4.57.55 PM.png](https://raw.githubusercontent.com/timothywongej/ped/main/files/1423593f-3500-4a00-8717-0eda703c9fbe.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: timothywongej/ped#9

**Comment by JeffZincatz** [comment]
Issue #207 refers to this same issue.
