### ISSUE TITLE
[PE-D] Sorting of interviews a candidate has is by date but not time 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-1/tp#214]
Just a suggestion! Perhaps sort by time after sorting by date for user readability. 

![Screenshot 2021-10-29 at 5.05.02 PM.png](https://raw.githubusercontent.com/timothywongej/ped/main/files/f3053a79-f141-4191-a246-6c2bc33e1b2d.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: timothywongej/ped#10

**Comment by angnobel** [comment]
New feature
