### ISSUE TITLE
[PE-D] Edit interview bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W13-1/tp#215]
Editing the interview does not reflect in 8.Bryan Tan

![image.png](https://raw.githubusercontent.com/zihaooo9/ped/main/files/a23098d4-33f7-4308-ba99-aa403bb20ded.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zihaooo9/ped#12

**Comment by angnobel** [comment]
Duplicated
