### ISSUE TITLE
DG Typo

### ISSUE THREAD

**Issue by angnobel** [AY2122S1-CS2103T-W13-1/tp#286]
![image](https://user-images.githubusercontent.com/52357548/140636536-b8977616-b700-49ae-b949-3e436d6fbe3e.png)
 Number of interviews not candidates

**Comment by wanyu-l** [comment]
![Screenshot (274)](https://user-images.githubusercontent.com/77219362/140639871-e71aa72b-f801-411a-92e0-3b7d23f7fc9b.png)
"You can... from **teh start**..."
"Alternatively, you can quickly get started by ^reading^ through...~~a~~ an overview"

**Comment by wanyu-l** [comment]
![Screenshot (275)](https://user-images.githubusercontent.com/77219362/140640035-29c0f662-3893-4f02-bd2d-ca086f4f52bd.png)
diagram displays `delete_c 1` but text displays `delete 1`

**Comment by wanyu-l** [comment]
![Screenshot (277)](https://user-images.githubusercontent.com/77219362/140640098-b0b9b3f6-776d-47b1-9b8e-b3b3613b193e.png)
different spelling of `ArgumentTokenizer`

**Comment by wanyu-l** [comment]
![Screenshot (278)](https://user-images.githubusercontent.com/77219362/140640219-ef098d9a-b18a-4c5a-83da-a5aaf72c5bc1.png)
"i" is not capitalised in `editinterviewDescriptor`
