### ISSUE TITLE
Add Manual test case in DG

### ISSUE THREAD

**Issue by seaweediman** [AY2122S1-CS2103T-W13-1/tp#306]
![image](https://user-images.githubusercontent.com/61644924/140687239-0c727a7e-bc8e-4fcf-b173-74dad14d05cc.png)

**Comment by JeffZincatz** [comment]
Position

**Comment by wanyu-l** [comment]
Interviews

**Comment by seaweediman** [comment]
candidates

**Comment by seaweediman** [comment]
### Candidate Management

#### Add a candidate

1. Adding a candidate
   i. Prerequisites : There must not be candidate with `Email` 'johnd@example.com' inside HR Manager. There must be an `Accountant` position in HR Manager.
   ii. Test case: `add_c name=John Doe phone=98765432 email=johnd@example.com address=311, Clementi Ave 2, #02-25 position=Accountant`
       Expected: Candidate John Doe is added to HR Manager. Details of the added candidate shown in command feedback box.
	   
2. Adding a candidate applying for a position that does not exist in HR Manager.
   i. Prerequisites : There must not be candidate with `Email` 'johnd@example.com' inside HR Manager. There must be an `Accountant` position in HR Manager. There must not be a `Bookkeeper` position.
   ii. Test case: `add_c name=John Doe phone=98765432 email=johnd@example.com address=311, Clementi Ave 2, #02-25 position=Bookkeeper`
	   Expected: Candidate is not added. HR Manager states that `Bookkeeper` does not exist in HR Manager.
   
#### List all candidates

1. Listing all candidates
    i. Prerequisite : There must be at least 1 candidate inside HR Manager.
	ii. Test case: `list_c`
		Expected: All candidates are listed in HR Manager.
		
#### Delete a candidate

1. Deleting a candidate
	i. Prerequisite: There must at least 1 candidate inside HR Manager.
	ii. Test case: `delete_c 1`
	    Expected: First candidate in the list is deleted from the list. Details of the deleted candidate shown in the command feedback box.

2. Entering an invalid candidate index
    i.  Prerequisite: There must at least 1 candidate inside HR Manager
	ii. Test case: `delete_c 0`
		Expected: No candidate is deleted. HR Manager states that the candidate index must be a non-zero unsigned integer.

#### Remark a candidate

1. Remarking a candidate
   i. Prerequisite: There must at least 1 candidate inside HR Manager.
   ii. Test case: `remark_c 1 remark=Great past experiences`
       Expected: First candidate in the list is given the remark and the remark is displayed together with the candidate's other details. Details of the remarked candidate shown in command feedback box.
	   
2. Entering an invalid candidate index
   i.  Prerequisite: There must at least 1 candidate inside HR Manager
   ii. Test case: `remark_c 0 remark=Great past experiences`
	   Expected: No candidate is remarked. HR Manager states that the candidate index must be a non-zero unsigned integer.

#### Edit a candidate

1. Editing a candidate
   i. Prerequisite: There must be at least 1 candidate inside HR Manager.
   ii. Test case : `edit_c 1 name=Aiken Lee`
       Expected: First candidate in the list has their name edited to Aiken Lee. Details of the editedd candidate shown in the command feedback box.
	   
2. Editing a candidate's position to a position that does not exist in HR Manager.
   i. Prerequisite: There must not be a `Bookkeeper` position in HR Manager.
   ii. Test case : `edit_c 1 position=Bookkeeper`
	   Expected: Candidate is not edited. HR Manager states that `Bookkeeper` does not exist in HR Manager.

####Find a candidate

**Comment by JeffZincatz** [comment]
### Position Management

#### Add a position

1. Adding a position
    1. Prerequisite: There must not be a position with `title` 'Software Tester' inside HR Manager.
    2. Test case: `add_p title=Software Tester status=open`
    Expected: Position Software Tester with open status is added to HR Manager. Details of the added position are shown in command feedback box.
	   
2. Adding a position with a title already existing in HR Manager.
    1. Prerequisite: There must be a position with `title` 'Software Tester' inside HR Manager.
    2. Test case: `add_p title=Software Tester`
    Expected: Position is not added. HR Manager states that `Software Tester` already exists in HR Manager.
   
#### List all positions

1. Listing all positions
    1. Prerequisite: There must be at least 1 position inside HR Manager.
    2. Test case: `list_p`
    Expected: All positions are listed in HR Manager.
		
#### Delete a position

1. Deleting a position
    1. Prerequisite: There must be at least 1 position inside HR Manager.
    2. Test case: `delete_p 1`
	    Expected: The first position in the list is deleted from the list. Details of the deleted position shown in the command feedback box.

2. Entering an invalid position index
    1.  Prerequisite: There must be at least 1 position inside HR Manager
    2. Test case: `delete_p 0`
    Expected: No position is deleted. HR Manager states that the position index must be a non-zero unsigned integer.

3. Not entering any position index
    1.  Prerequisite: There must be at least 1 position inside HR Manager
    2. Test case: `delete_p`
    Expected: No position is deleted. HR Manager states that the command format is invalid.

#### Edit a position

1. Editing a position's title
    1. Prerequisite: There must be at least 1 position inside HR Manager.
    2. . Test case: `edit_p 1 title=Librarian`
    Expected: The first position in the list has its position edited to 'Librarian'. Details of the edited position are shown in the command feedback box.
	   
2. Editing a position's title to one that already exists in HR Manager.
    1. Prerequisites: There must be a 'Software Tester' position in HR Manager. The first position's title is not 'Software Tester'.
    2. Test case: `edit_p 1 name=Software Tester`
    Expected: The position is not edited. HR Manager states that the position already exists in HR Manager.

3. Editing a position's status
    1. Prerequisite: There must be at least 1 position inside HR Manager.
    2. Test case: `edit_p 1 status=closed`
    Expected: The first position in the list has its status edited to 'closed'. Details of the edited position are shown in the command feedback box. Any candidate with this position will have their position removed.
	   
2. Editing a position's status to an invalid one.
    1. Prerequisite: There must be at least 1 position inside HR Manager.
    2. Test case: `edit_p 1 status=invalid`
    Expected: The position is not edited. HR Manager states that the position status can only be open or closed.

#### Find positions

1. Find positions by title
    1. Prerequisite: At least 1 position with the title containing keyword 'Software' inside HR Manager.
    2. Test case: `find_p title=Software`
    Expected: All positions whose title contains 'Software' are listed.

2. Find positions with a title not in HR Manager
    1. Prerequisite: No position with the title containing the keyword 'Accountant' inside HR Manager.
    2. Test case: `find_p title=Accountant`
    Expected: No position is listed.
